### ISSUE TITLE
401 Authorization error

### ISSUE THREAD

**Issue by rameshelamathi** [klarna/kco_rest_php#22]
**Describe the bug**
401 Authorization error

**Which service do you use**
Klarna Checkout

**To Reproduce**
The bug occurs even with the latest 4.1.2 version. 
1. Just use the 4.1.2 package
2. Use the create_checkout.php example in the docs folder
3. Just replace the Merchant ID and shared secret. even for valid credentials, 401 occurs

**Comment by alexions** [comment]
Hi @rameshelamathi 

Please make sure that you use the proper Klarna endpoint. By default the example you mentioned uses 
Klarna\Rest\Transport\ConnectorInterface::EU_TEST_BASE_URL (https://api.playground.klarna.com)

This is EU Playground endpoint. Make sure that you use the Credentials for EU Playground and not for US playground or for Production one.

**Comment by rameshelamathi** [comment]
Yes. We are using the proper endpoint.
Klarna\Rest\Transport\ConnectorInterface::EU_BASE_URL

Just to be sure, i tested with all end points as well. The error occurs. 
A customer of ours reported the issue. We tested and gave him the package with the sample code (replaced with his credentials) and asked him to send it to you guys as well.

**Comment by rameshelamathi** [comment]
Klarna\Rest\Transport\ConnectorInterface::EU_BASE_URL
Klarna\Rest\Transport\ConnectorInterface::EU_TEST_BASE_URL
Klarna\Rest\Transport\ConnectorInterface::NA_BASE_URL
Klarna\Rest\Transport\ConnectorInterface::NA_TEST_BASE_URL

Tested the credentials received by the customer from his Klarna account dashboard.
And he confirmed that he has Checkout V3 enabled for him, multiple times and also checked with your support

**Comment by alexions** [comment]
Can you please check the code with your own playground account credentials? You can easily create a new account here: https://playground.eu.portal.klarna.com/developer-sign-up

It's free and very quick. After getting an account, just go to Credentials section to generate a new API keys: https://playground.eu.portal.klarna.com/settings/credentials

**Comment by rameshelamathi** [comment]
Mate, 

You are not getting my point. And customers are getting irritated. 
So it would be great if you first test it and then get back to me.

Playground is NOT a problem. Please use a Live credential to test.

Your very own PHP SDK does not work with Checkout V3 

Here are the steps to re-produce the issue.

1. Take a LIVE account credentials
2. Use this example to create a checkout (your very own example):  https://github.com/klarna/kco_rest_php/blob/v4.1/docs/examples/CheckoutAPI/create_checkout.php

And you will get this error :
Caught exception: Client error: `POST https://api.klarna.com/checkout/v3/orders` resulted in a `401 Unauthorized` response 

Hope you can take a serious look into it.

Thanks
Ramesh

**Comment by alexions** [comment]
We checked the SDK code and our API responses. This is neither a technical issue nor an SDK issue.

Please contact Klarna technical support via the Klarna Contact Us form (https://klarna.com/).

**Comment by jidefela** [comment]
@rameshelamathi Buddy, how did you go about this issue ? I'm certain the issue is with Klarna API. 
 I'm sending the same payload to the US_PORTAL and that works quite well. Any pointers ?

**Comment by gidaban** [comment]
Hello Guys i know is really late however i contact directly with support, and answer whit i got:

Below the instruction.  

Please complete the following steps, so that we can set your Merchant-ID live: 

1. Integrate Klarna Checkout 

Instruction for integration of Klarna Checkout with our API interface: 

https://developers.klarna.com/en/de/kco-v3/checkout 

 SDK: https://developers.klarna.com/en/de/kco-v3/download/php 


Under following link you can find the Order Management Calls: 

https://developers.klarna.com/en/de/kco-v3/order-management 

Please first use your test MID from the Klarna Playground Portal under the app "Settings" (Playground Merchant Portal). Only when all tests have been successful, we can set your Live API Credentials live. That's how long you are at Klarna in test mode. 

2. Terms & conditions 
Include the Klarna legal text in your terms and conditions. If you use the terms and conditions of a third-party provider and therefore can not adjust their terms and conditions, insert Klarna in your online shop section "Terms of payment". 

The legal texts to be shown to the customer can be found at: 
https://developers.klarna.com/documentation/klarna-checkout/legal-privacy 

Please insert the terms and conditions only for the payment methods that you offer through Klarna in the respective sales countries. Please also pay attention to the links "here", since you also have to insert your MID (../EID/ ..) under the URL. 

3. Klarna logo 
Paste the Klarna logo on the start page in the footer. The logo can be found here: 
https://developers.klarna.com/resources/branding-visuals/ 

4. Shop logo 
Please log in to the Klarna Merchant Production Portal (Merchant Portal) and upload your shop logo and your icon. To do this, go to the portal on the app "Branding". 

5. Beneficial Owner Information Request 
Please fill out the online form "Anti-Money Laundering Act (AML-Mail)", otherwise we can not transfer money from the transactions to your bank account. You received an email from our head office together with the "Welcome Mail". If you have not received them, please contact us by email. 

6. Payment instruction- Zahlungsinformation 
When you set the order to completed we will send the payment information to the customer. Please do not send any bank data in your invoice. 
Please add the following text to your invoice: 
Die Zahlung wird durch unseren Partner Klarna abgewickelt. Bitte beachten Sie die von Klarna versandten Zahlungsinformationen. Sie können all Ihre Einkäufe über Klarna.com bzw. die Klarna App verwalten und sogar mit nur einem Klick bezahlen. 



7. Appointment for Live Approval 
If the steps (above) are completed and visible in the frontend, please send me an email for a quick feedback. I will then check your integration. It is necessary that I carry out a test order. Afterwards, we will discuss and test the Order Management to check whether the shipping of goods and the refunds are correctly transmitted to us. 

If you have further questions, please do not hesitate to contact me. 

Best regards,

**Comment by lordmoyne** [comment]
We had the exact same issue and struggled to find a solution.

Turns out we had chosen 'Klarna Payments' instead of 'Klarna Checkout' when signing up for a Merchant ID.

**Comment by pdahlberg** [comment]
Couldn't figure out what was wrong with the production integration until I read your answer @lordmoyne. Thanks for writing this! Turns out the customer had created the wrong type of account even though they were told to create a checkout account. 

Feature request to Klarna: Show the type of account or a list of the account's capabilities in the admin interface. Or as an alternative add an info request to the API that returns the capabilities of the account.
