### ISSUE TITLE
Payments Session ID is reset after fetch()

### ISSUE THREAD

**Issue by mpesari** [klarna/kco_rest_php#37]
**Describe the bug**
I'm not sure whether this is a bug or an undocumented(?) feature.

I'm trying to use an existing Payments Session if possible. I accidentally ended up creating a new session every time, because I did some checks on  `$session->getId()`. Use case here is e-commerce checkout page.

**Which service do you use**
Klarna Payments

**To Reproduce**

1. Customer comes to checkout page for the first time: create a new session, save id somewhere
```php
$session = new \Klarna\Rest\Payments\Sessions($connector, null);
$session->create($data);
$session_id = $session->getId(); // "foo-bar-123"
```

2. User goes away and comes back to checkout page: update existing session
```php
$session = new \Klarna\Rest\Payments\Sessions($connector, $session_id);
var_dump($session->getId()); // "foo-bar-123"

$session->update($data);
var_dump($session->getId()); // "foo-bar-123"

// get payment_method_categories etc. because they are not populated by update()
$session->fetch();
var_dump($session->getId()); // NULL
```

**Expected behavior**
I would expect the session ID not change to `null`. It happens in `Resource::fetch()` because the API returns data that doesn't include the ID. Local workaround was to store the ID before `exchangeArray()` and apply it back afterwards.

https://github.com/klarna/kco_rest_php/blob/f9141df578c05a6ddbfbee1417a6c668f4635ae6/src/Klarna/Rest/Resource.php#L121

**Additional context**
`klarna/kco_rest` v4.1.5

**Comment by alexions** [comment]
Hi @mpesari 

I can confirm this behaviour and you explained this issue well! The problem is with the API consistency unfortunately. In most cases the APIs return the ID key field, so we can safely exchange the fields (probably, with updated/changed ID), but not in this case.

The solution you proposed looks quite good and I will try to implement this in the nearest time. But at the same time I will try to reach the Klarna Payment API team to add a session_id to response.

Thanks for the feedback!

**Comment by alexions** [comment]
https://github.com/klarna/kco_rest_php/pull/38
