### ISSUE TITLE
Unexpected reponse HTTP status 401. Excepted HTTP status should be in 2xx range

### ISSUE THREAD

**Issue by gidaban** [klarna/kco_rest_php#41]
Hi,

Very strange issue,

When i am using 'EU_TEST_BASE_URL' for testing checout everything worrking well,
however when i am switch to 'EU_BASE_URL'

i am getting this error.

Before you will ask yes i am changing login and password after change URL.

![klarna](https://user-images.githubusercontent.com/1633884/63435348-aeaac180-c41e-11e9-8771-399a480d8a19.png)

Any solutions ?

**Comment by jidefela** [comment]
@gidaban Did you manage to resolve this ?

**Comment by alexions** [comment]
Hello guys!

I will try to summarize the information about the Unauthorized issue. In general we have 3 possible situations when you can get this response:

1) You already mentioned this: Changing the credentials to a production one. It's the most common issue. Yep, playground credentials will not work for production. But this is not your case.
2) The second possible issue - a typo. Sometimes it can be a space or a tab symbol or just missing chars.
3) I think you have this point: This not an obvious issue and it's hard to determine from your side. You/your company have to have a signed contract with Klarna to have a specific product. And this is a tricky part, because you can sign a contract to have, let's say, a Klarna Checkout product, but you try to integrate Klarna Payment product. Despite the fact that you have an access to the Merchant Portal, you were able to get the production credentials, you still cannot use the Klarna Payment because there is no signed contract between your company and Klarna. In this case even using the right credentials you will get "401 Unauthorized".

We have no such limitations for the Playground and in most cases* you can use all the Klarna products there and you can play well with Klarna Checkout or Klarna Payment or other products.

So I would suggest you to do 2 things:
1) Make sure, that you really can use the product (you have a signed contract) that you try to integrate
2) You can contact the Klarna Support team via klarna.com contact us form. They will help you with your integration issue.

I hope my answer will help you to solve the problem!
It would be nice if you provide the result.

Best wishes!

**Comment by alexions** [comment]
I forgot to share the link: https://klarna.com/merchant-support

By clicking this link you will be redirected to a country-specific support page where you can use Chat/Phone/Email/etc to contact the support team.

**Comment by alexions** [comment]
I will consider this issue as closed. Feel free to reopen in case if you have any questions.

**Comment by jidefela** [comment]
The problem (at least in my case) was that, I had been using the API credentials for a different product. Check your merchant dashboard to be sure which Klarna product your API key is created for. 

Good luck.
