### ISSUE TITLE
Is this still in development?

### ISSUE THREAD

**Issue by rockymontana** [klarna/kco_rest_php#9]
The last commit dates back to  Dec 2015.
Is this the official KCO package that should be used?
Since your guzzle package requirement is older than Gandalf it seems to be somewhat archived, but maybe that's not the case?

Do you plan on any new release soon for this?

**Comment by bubach** [comment]
> Since your guzzle package requirement is older than Gandalf

😂 

I'm trying to get this working (PHP7 + Guzzle v6) and have a fork working for the first example (creating and fetching order) https://github.com/Ridestore/kco_rest_php/commits/guzzle6

I don't think I've broken support for older versions of Guzzle, but had to remove some typehinting on Request/Response due to the newer version going Psr7.

**Comment by mitemitreski** [comment]
@rockymontana @bubach  we are looking to modernising this, stay tuned
